// Generated by https://quicktype.io

export interface RankingsResponse {
    rank:         number;
    value:        number;
    second_value: number;
    kickers:      number[];
    cards_used:   Card[];
    cards:        Card[];
}

export interface Card {
    rank: string;
    suit: Suit;
}

export enum Suit {
    Diamonds = "diamonds",
    Spades = "spades",
    Hearts = "hearts",
    Clubs = "clubs",
}
